@arr=("a","b","c","d","e","f","g","h","i","j");
print "The original array is @arr\n";
push(@arr,"h");
print "With push Operation we inserting at end  @arr\n";
pop(@arr);
print "with pop we deleting at end @arr\n";
shift(@arr);
print "with shift operation we deleting at front  @arr\n";
unshift(@arr,"a");
print "with unshift operation we adding at front @arr\n";
@first=@arr[0 .. 4];
@second=@arr[5 .. 9];
print "we splitting array into two \n First: @first \n Second: @second\n";
@new=("caroline","daemon","elena");
splice(@arr,2,3,@new);
print "After replacing @arr\n";
$str=join("!!!!!",@arr);
print "Convertion of array to string $str\n";
@new_arr=split("!!!!!",$str);
print "Convertion of string to array @new_arr\n";
@arr2=("one","two","three","four","five","six","seven");
print "Before sorting: @arr2\n";
@arr3=sort(@arr2);
print "After sorting: @arr3\n";
@arr4=reverse sort(@arr2);
print "Reverse sorting: @arr4\n";
@final=(@arr3,@arr4);
print "Merging: @final\n";
@dig=qw(1 2 3 4 5 6 7);
@dig1=map {$_ *5} @dig;
print " @dig1\n";

